schema = 3

[mod]
  [mod."cel.dev/expr"]
    version = "v0.25.1"
    hash = "sha256-TEdMxFUPK7IZuCXMufwCkbN+ZZIXSQclljIybFZcByo="
  [mod."cloud.google.com/go"]
    version = "v0.123.0"
    hash = "sha256-OjuvlqYrGvoUiXO/5ALbMxHvXRlrhDjLby1BN/nuhAw="
  [mod."cloud.google.com/go/auth"]
    version = "v0.19.0"
    hash = "sha256-o1IkZKdpnhWaYiqK0v4Aj+v2VZdJgxFfKQwq3Nf9978="
  [mod."cloud.google.com/go/auth/oauth2adapt"]
    version = "v0.2.8"
    hash = "sha256-GoXFqAbp1WO1tDj07PF5EyxDYvCBP0l0qwxY2oV2hfc="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.9.0"
    hash = "sha256-VFqQwLJKyH1zReR/XtygEHP5UkI01T9BHEL0hvXtauo="
  [mod."cloud.google.com/go/iam"]
    version = "v1.6.0"
    hash = "sha256-em8PslcxZ03qJgqZyAV2ZxFxY4xG7io39MOv5V37HLY="
  [mod."cloud.google.com/go/monitoring"]
    version = "v1.24.3"
    hash = "sha256-glEOr2xKDIHqQx76mFg9JdS6/PRvXLBZhEtGn6RPT34="
  [mod."cloud.google.com/go/storage"]
    version = "v1.61.3"
    hash = "sha256-J2L6nc/ULAOVpmkj+lOgk2J9LZF2jD9Av5feqs0KIDM="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp"]
    version = "v1.31.0"
    hash = "sha256-KeDm6O9FKL78kuZQhqoOfY00m0rYkxB1gtoKZzx+nGs="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric"]
    version = "v0.55.0"
    hash = "sha256-a9I5LzWtYVjKo0gA7wZGEKTEECtU1cmOyuCHomX/LLo="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/internal/resourcemapping"]
    version = "v0.55.0"
    hash = "sha256-jP3icdVicaP1gKle5nYqctC9elzEJ5VmH/aexBkudBM="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y="
  [mod."github.com/ardanlabs/conf/v3"]
    version = "v3.11.0"
    hash = "sha256-bDinrupedF1KLY2WUTnpCcsIXQeiBvE6kCdsusXD+6k="
  [mod."github.com/arl/statsviz"]
    version = "v0.8.0"
    hash = "sha256-rSItFJKW0u0LxOU0li9jR9vGeSM+R9tGVEktsuo8t5Q="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.41.5"
    hash = "sha256-gPtAxzRKF5Uep8f1NElsuXrWVePOoU3bxfPv5CRDwvI="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.7.8"
    hash = "sha256-UW9P6XKdTv9MXG8NcnZFli6RVZ1s6LXfD9j3EUBr1FE="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.32.13"
    hash = "sha256-yjFyybCnTPJAWvp69SgRN0eoy6hOLEGlT5ChrbgVGI0="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.19.13"
    hash = "sha256-M/+OMPWaAII/8vcRyZyvu8VskCYFGkAPJk0hccHvBSk="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.18.21"
    hash = "sha256-KIQqh21N0WhlDs5hM+Sle3IocWHgn9F9oYwl70/t8ko="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.4.21"
    hash = "sha256-oVZq0A/muPG2CKD1HLeQ/kuHAESSSwbIFB9V181tKCc="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.7.21"
    hash = "sha256-M4SiYSVAQU3wXKdIc0aW2Mv2zgGwXvd/+3oyqRKzKQc="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.6"
    hash = "sha256-oIRPqu99vnGINAWKnCEytpv7N0gRWO7S72tb1r8oxvk="
  [mod."github.com/aws/aws-sdk-go-v2/internal/v4a"]
    version = "v1.4.22"
    hash = "sha256-wyrKI56LVsMu626WbL9Qvjpo4IA8juBSq7d+k0/Dw+M="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.13.7"
    hash = "sha256-AfYJdpmnW01Bk/jfHATlNU6lddjqcigFkHw/zcT9WO4="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/checksum"]
    version = "v1.9.13"
    hash = "sha256-DJLN7WoTwz215VzrdIb+5gXWdavjpQlaZrlhl4BbTro="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.13.21"
    hash = "sha256-FE2sj0e8hoQ9cVzCnbGRZF068hkQI3Om9yUB/kEB+H0="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/s3shared"]
    version = "v1.19.21"
    hash = "sha256-tbALcmFnnU+Y8NgTJzStS6T8naV92M2skgNXY8Rmem4="
  [mod."github.com/aws/aws-sdk-go-v2/service/s3"]
    version = "v1.97.3"
    hash = "sha256-JXleyDC4n+nISJqRzABASdnPMe2PDXK5a3qO/xYpD20="
  [mod."github.com/aws/aws-sdk-go-v2/service/signin"]
    version = "v1.0.9"
    hash = "sha256-K2n7i40z1gnT6xVWrFUSGG1y0guHzY+cD1MipLWU1F8="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.30.14"
    hash = "sha256-Rr6OY4jbYlNo8M2YMHdZn7ByCtakzOk3pJWhrj29qxs="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.35.18"
    hash = "sha256-Ku48Uc37zR7hHvXv5q9Mg1roTxQbSLWmN+zZrGPQGqY="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.41.10"
    hash = "sha256-T1F3RJd3iQSkCBI/jYmHrXi2JMWWuRCuYIymlXFhylI="
  [mod."github.com/aws/smithy-go"]
    version = "v1.24.2"
    hash = "sha256-v0y+Lir61fgdCwdVoca5mK+FcGh9OD3cTEwHIfLytcI="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bgentry/go-netrc"]
    version = "v0.0.0-20140422174119-9fd32a8b3d3d"
    hash = "sha256-NDxQzO5C5M/aDz5/pjUHfZUh4VwIXovbb3irtxWCwjY="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/cncf/xds/go"]
    version = "v0.0.0-20260202195803-dba9d589def2"
    hash = "sha256-nCcna5Dwr8a+FgdSZt43VmoMds5U0FZta2vpJfdMOhs="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.4.1"
    hash = "sha256-FfHNUmNdqtxHP5OFxqlJJ5jiZ9unpjeLGJS2yHoaNfU="
  [mod."github.com/dgraph-io/badger/v4"]
    version = "v4.9.1"
    hash = "sha256-izmptzOGBB8YWUYLphkfZuJ7qxAGRney0Tx4Ayyppn0="
  [mod."github.com/dgraph-io/ristretto/v2"]
    version = "v2.4.0"
    hash = "sha256-U7lgRlPXM3IZWaVeoiEpZinBRfVR5jVHzM5GEOonj0U="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/ebitengine/purego"]
    version = "v0.10.0"
    hash = "sha256-NPS88SNvsm4QEAx1zVmNGzMwtR1EBhdQYywQU1JdRqM="
  [mod."github.com/envoyproxy/go-control-plane/envoy"]
    version = "v1.37.0"
    hash = "sha256-xxQd6objJVXpcQ8B7MznhqeQLoLWlyjlASnq2hJDp+k="
  [mod."github.com/envoyproxy/protoc-gen-validate"]
    version = "v1.3.3"
    hash = "sha256-NsI6A4CBVTpAq4gsmv66sMx0gvY0J0kF/t9zbtlRLr4="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.1.3"
    hash = "sha256-WfogdTIRu4yDtCVX5fzz/+kKVPwX/hXBl+nY31XFHNc="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/gobwas/glob"]
    version = "v0.2.3"
    hash = "sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.6"
    hash = "sha256-/REW1EDZ3Ta45hrDNR9YTIlhkxQQI8OeK5TxBNJ47Ho="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.2"
    hash = "sha256-rTSqYEPooi8Uu4aXMW6k9dynOV+URYTGzVmbG3EQ7uo="
  [mod."github.com/google/flatbuffers"]
    version = "v25.12.19+incompatible"
    hash = "sha256-NOYL9CWJgjdY1u4j/Ccyz2i50RjvZfNm/K+EFj7GIYk="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/jsonschema-go"]
    version = "v0.4.2"
    hash = "sha256-kNExU/AI+CS27tQntXEpFqSio+HV2wzo2P458jqncOk="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.9"
    hash = "sha256-0AdSpSTso4bATmM/9qamWzKrVtOLDf7afvDhoiT/UpA="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.3.14"
    hash = "sha256-yuNtkMq+gqN1vZ9alekxe47vAEbTCBHXO6Mwwv/lwrE="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.20.0"
    hash = "sha256-7ulvDVmPUHY86INQ2UjfY48zOlB1X08V3o/JUBN1mOI="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.28.0"
    hash = "sha256-QeWb6jN6noeGPCzECgpUSb9YX9LzvKGwImEuX+A03gs="
  [mod."github.com/hashicorp/aws-sdk-go-base/v2"]
    version = "v2.0.0-beta.72"
    hash = "sha256-Q1RQJJrLrBm8vND4QnvUX52hSKd6fHclwB0vM7kdkAc="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-getter"]
    version = "v1.8.5"
    hash = "sha256-K60b32SLt/MMk6XBE9GHnFQI42VaHMIOjPdu9qMvxFs="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.9.0"
    hash = "sha256-sRr/50k8Wra0PJLCJgSkIxvR+ce3PItx4HpFvVijGYk="
  [mod."github.com/hybridgroup/yzma"]
    version = "v1.11.1"
    hash = "sha256-bHXl8iK2+1ByZDVDRWyUlvBq79jImjJrP/hayKeh01c="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/jupiterrider/ffi"]
    version = "v0.6.0"
    hash = "sha256-jseugdznEwzAj9rBZqkjgM07Ub4rBQmRSDLNNJ06ysA="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.5"
    hash = "sha256-H9b5iFJf4XbEnkGQCjGQAJ3aYhVDiolKrDewTbhuzQo="
  [mod."github.com/lestrrat-go/blackmagic"]
    version = "v1.0.4"
    hash = "sha256-HmWOpwoPDNMwLdOi7onNn3Sb+ZsAa3Ai3gVBbXmQ0e8="
  [mod."github.com/lestrrat-go/dsig"]
    version = "v1.0.0"
    hash = "sha256-7rDk/0QwBiT4swzaGjBp/CGwYDNz34gmCKDA85VgO5Q="
  [mod."github.com/lestrrat-go/dsig-secp256k1"]
    version = "v1.0.0"
    hash = "sha256-kKdirGAHjx0lZPGPJCsvRVqPGTlFUGcF1SIvtXkUJRo="
  [mod."github.com/lestrrat-go/httpcc"]
    version = "v1.0.1"
    hash = "sha256-SMRSwJpqDIs/xL0l2e8vP0W65qtCHX2wigcOeqPJmos="
  [mod."github.com/lestrrat-go/httprc/v3"]
    version = "v3.0.5"
    hash = "sha256-BWOPRiSatj9NDaC12kz2juYCQjyQ0qxVUOQHMdh1HdY="
  [mod."github.com/lestrrat-go/jwx/v3"]
    version = "v3.0.13"
    hash = "sha256-OY6otUXRelAKfTzabhL6c4oiCrP/iBdZQbSsGb2q9G0="
  [mod."github.com/lestrrat-go/option/v2"]
    version = "v2.0.0"
    hash = "sha256-ZmegDY7E3+tLd+kkNal1aeq3nfNH/dlWPpXOJfI3L5Q="
  [mod."github.com/maypok86/otter/v2"]
    version = "v2.3.0"
    hash = "sha256-ELzmi/s2WqDeUmzSGnfx+ys2Hs28XHqF7vlEzyRotIA="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/modelcontextprotocol/go-sdk"]
    version = "v1.4.1"
    hash = "sha256-YTU5X1mbplYKXDad6vVbPBlleNR60bXVSeVjAE7QYMw="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/nikolalohinski/gonja/v2"]
    version = "v2.7.0"
    hash = "sha256-ego5VX/72VPBL+Tmz+rH5rM+ZzLaEt+pVTo+oOioMmI="
  [mod."github.com/open-policy-agent/opa"]
    version = "v1.15.1"
    hash = "sha256-laaRgKevNqdbn7hr36iRy5WmshCKR9gTNdVoWoGcd8Q="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/planetscale/vtprotobuf"]
    version = "v0.6.1-0.20240319094008-0393e58bdf10"
    hash = "sha256-L8dyNm+PCRDNADiIGKZqsPkCgB4xpLrosZjssrN+sUY="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.67.5"
    hash = "sha256-pDzmYsAANsaIf3W9HxpbgRnZ4BkPhJBBwzKq2E58FRw="
  [mod."github.com/prometheus/procfs"]
    version = "v0.20.1"
    hash = "sha256-L6RuVGYgdBCCke8BibA7cXgfwizGE2pA0gNo9dGJ8WQ="
  [mod."github.com/rcrowley/go-metrics"]
    version = "v0.0.0-20250401214520-65e299d6c5c9"
    hash = "sha256-xTuRRrDpI/ANi/cvRMerx+gHP/ePGT0MxHHB5UXMVus="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.1"
    hash = "sha256-XhAJObkSa7gjx3PqYrreVEcMHBc/rDVeY/lWvNccGB0="
  [mod."github.com/segmentio/encoding"]
    version = "v0.5.4"
    hash = "sha256-AVIwCIh/L7X7CaGGX2gYOlurO/xifjjLpK+AIRTv2rQ="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.4"
    hash = "sha256-ltRvmtM3XTCAFwY0IesfRqYIivyXPPuvkFjL4ARh1wg="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spiffe/go-spiffe/v2"]
    version = "v2.6.0"
    hash = "sha256-8fvyGwDgSAFebzE1TA/cMTsFjH2CgxvHP5WoPfhw4Fk="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/tchap/go-patricia/v2"]
    version = "v2.3.3"
    hash = "sha256-6Ahy1QFyx3T0z5zghIGWBgfagdRGPLgrKYYcYvJj2ig="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.15"
    hash = "sha256-L5KYLue5U14bxUuNyhZ6lIjbda6eCQsx1V6gToqfRdk="
  [mod."github.com/valyala/fastjson"]
    version = "v1.6.10"
    hash = "sha256-D2lL4FnkeL/eRLiRW6ihhqQkzEqHVvhbEvZoYTVNmbU="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.5.32"
    hash = "sha256-bX/2o83+cKZJzA3c3bpzc2KLfogJ3qh1kEEjCmDQkeo="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20190905194746-02993c407bfb"
    hash = "sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g="
  [mod."github.com/xeipuuv/gojsonreference"]
    version = "v0.0.0-20180127040603-bd5ef7bd5415"
    hash = "sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU="
  [mod."github.com/yashtewari/glob-intersection"]
    version = "v0.2.0"
    hash = "sha256-SwTh5MEtGTqytNqlvoMWaEpVx9iABnnBJ6FzLJ5qg+s="
  [mod."github.com/yosida95/uritemplate/v3"]
    version = "v3.0.2"
    hash = "sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/contrib/detectors/gcp"]
    version = "v1.42.0"
    hash = "sha256-t/C8HDYw0zKSF+X8je/HEMEdqHE1vv2X6E5xvFaMQKk="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.67.0"
    hash = "sha256-jaeaZWa0vUtrRCyLwZ+RubYCVy/CUrUzGXhMkYcargA="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.67.0"
    hash = "sha256-efihYJm1SmM0T+n4e8MsUtTS5yAROK8svGwPAycd7fA="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.42.0"
    hash = "sha256-7dck3F+khfda+U8PLSJTVETFl/M/mjXboBOsDCtF5aQ="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.42.0"
    hash = "sha256-aDdq1I8vj7i2vC1dB0HriiJ1V+dZUq2Bmj21L2avmlU="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.42.0"
    hash = "sha256-fxmGkDhYVBENoLdpbV1Vhy3ShGJedhxMs/zbnflKUfg="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.42.0"
    hash = "sha256-OabGeuj05yLHN917j30E0QO8x8fHuZoNeotgfbzIWIA="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.42.0"
    hash = "sha256-JJ/cXgaOzETb5EnM/HODhf2g4+9gnOg4x0m78KPMFNE="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.42.0"
    hash = "sha256-JaNMfKOHlvSqG/IZ92UIMBSCRlS7OHnJkVHp6vKkv70="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.42.0"
    hash = "sha256-WowP4UqkV5BDYVlw4pivWf3DPANLgTlVbwzpED371zw="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.10.0"
    hash = "sha256-IEnbR38ucFLTcuC2FA+gRvZNq2loUqXgDskSqP3+LUM="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.4"
    hash = "sha256-ecT2ZXw7iT+63J4210xA6sMz0fUFXmDzLwZe2FzaNFU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/crypto"]
    version = "v0.49.0"
    hash = "sha256-OW321Q3osc/qUOM6BsZGEjOqW1DrgakbIiQACCY/qUI="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20260312153236-7ab1446f8b90"
    hash = "sha256-q4a4MK4pVmaazKo9DTOwocH6Fvo8NsO96YeY9FJmNyo="
  [mod."golang.org/x/net"]
    version = "v0.52.0"
    hash = "sha256-TQYGkhRhldpi/eGRoDGi4xObh3xh1AuuX2c7uwL/V5Q="
  [mod."golang.org/x/oauth2"]
    version = "v0.36.0"
    hash = "sha256-evS7WkMrpgonmTcqtWFpC5rSKZN8O+vnAhNUs1MS9kw="
  [mod."golang.org/x/sync"]
    version = "v0.20.0"
    hash = "sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y="
  [mod."golang.org/x/sys"]
    version = "v0.42.0"
    hash = "sha256-LhNedvUEJbPYyR6EoU91rfOr3DBBoauLOcMcyqghEos="
  [mod."golang.org/x/text"]
    version = "v0.35.0"
    hash = "sha256-MXhEl0aLAyS+4SjQZMipoYKgNEOWdIYnr8h7WtLdTdQ="
  [mod."golang.org/x/time"]
    version = "v0.15.0"
    hash = "sha256-5D24A65wn7k93Jj3+918UKjB9ccmGHPBEqjD2XDB92E="
  [mod."google.golang.org/api"]
    version = "v0.273.0"
    hash = "sha256-sd4jvnkY9xZdzXtsklAVvdN9YHgr3M7jv5xERJ2xl4c="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20260319201613-d00831a3d3e7"
    hash = "sha256-FTEmDjXoUD/c9Tx9T79WNiiCuFPVbh8pzC/tUgfYPhI="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20260319201613-d00831a3d3e7"
    hash = "sha256-OmiDhqoKu+PLEn3hxnYqSmjPfCs6cgObHkky8ENgUOk="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20260319201613-d00831a3d3e7"
    hash = "sha256-pnGJ+eFKWgDoT8oYp88FEOaafs+WJe3vsZHyZLSj5pU="
  [mod."google.golang.org/grpc"]
    version = "v1.79.3"
    hash = "sha256-mO9ZI8ONBMEBTlrwIPeQMfb3C9ru5zPb26P+uG/pIzY="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.11"
    hash = "sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.6.0"
    hash = "sha256-49hg7IVPzwxeovp+HTMiWa/10NMMTSTjAdCmIv6p9dw="
